# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:13:10+00:00

from __future__ import annotations

from pydantic import BaseModel


class CallPhoneNumberAuthPostRequest(BaseModel):
    pass


class CompletePhoneNumberAuthPostRequest(BaseModel):
    pass


class CreateChannelPostRequest(BaseModel):
    pass


class FollowPostRequest(BaseModel):
    pass


class GetClubPostRequest(BaseModel):
    pass


class GetClubsForTopicPostRequest(BaseModel):
    pass


class GetCreateChannelTargetsPostRequest(BaseModel):
    pass


class GetFollowingPostRequest(BaseModel):
    pass


class GetOnlineFriendsPostRequest(BaseModel):
    pass


class GetProfilePostRequest(BaseModel):
    pass


class GetSuggestedClubInvitesPostRequest(BaseModel):
    pass


class GetSuggestedFollowsFriendsOnlyPostRequest(BaseModel):
    pass


class GetSuggestedFollowsSimilarPostRequest(BaseModel):
    pass


class GetSuggestedInvitesPostRequest(BaseModel):
    pass


class GetSuggestedSpeakersPostRequest(BaseModel):
    pass


class GetTopicPostRequest(BaseModel):
    pass


class InviteFromWaitlistPostRequest(BaseModel):
    pass


class InviteToAppPostRequest(BaseModel):
    pass


class JoinChannelPostRequest(BaseModel):
    pass


class LeaveChannelPostRequest(BaseModel):
    pass


class MePostRequest(BaseModel):
    pass


class RecordActionTrailsPostRequest(BaseModel):
    pass


class RefreshTokenPostRequest(BaseModel):
    pass


class ResendPhoneNumberAuthPostRequest(BaseModel):
    pass


class SearchClubsPostRequest(BaseModel):
    pass


class SearchUsersPostRequest(BaseModel):
    pass


class StartPhoneNumberAuthPostRequest(BaseModel):
    pass


class UpdateNotificationsPostRequest(BaseModel):
    pass


class UpdateUsernamePostRequest(BaseModel):
    pass
